### ISSUE TITLE
Festo Drive uitzoeken

### ISSUE THREAD

**Issue by tomreit1** [W-P-I/-Template_Repository-#1]
Festo drive voorbereiden, software schrijven zodat een virtual axis drive output tags direct moved kunnen worden naar de festo regelaar. 

uitkomst moet zijn. virtual axis aanmakne in logix designer en dat de festo drive alles qua positions / speed / accel & decel / jerk values direct mee lopen met de virtual axis. 

hiermee kan een festo drive gebruikt worden al een alternatief voor de kinetix regelaars.

**Comment by SanderBlaakmeer** [comment]
connectoren opzoeken dit heeft @engineerWPI tot zich genomen

**Comment by tomreit1** [comment]
@SanderBlaakmeer hoe lijkt dit jong, kom je er al wat verder mee?

**Comment by tomreit1** [comment]
Sander heeft overdracht gedaan naar richie

**Comment by SanderBlaakmeer** [comment]
Richie heeft alles aangesloten. Als je wilt beginnen met testen moet je alleen nog de 24VDC aansluiten van de enable. Deze is al voorbereid (ethernetkabel met hulsjes) die beide op de 24VDC aansluiten.
