### ISSUE TITLE
Git training

### ISSUE THREAD

**Issue by tomreit1** [W-P-I/-Template_Repository-#12]
### **Git training geven:** 
- Hoe werkt Git lokaal.
- Wanneer gebruik je git
- Waarvoor gebruik je git
- Hoe sla ik mijn software op in git
- Waar haal ik mijn software vandaan
- Hoe maak ik een repository aan volgens de juiste manier
- hoe werkt de agenda items. 
- wat is het verschil tussen agenda items en project specifiek items. 
- Krijg ik overal die mail van?
- Wat moet er allemaal in opgeslagen worden?
- Wat heb ik (Sander) eraan, kijkend naar mijn werkzaamheden?
- Wat kunnen we allemaal met Git?
- Moet Git ook altijd ''open'' staan?

**Comment by engineerWPI** [comment]
- hoe deel je een project in?
- waar kan ik de werkzaamheden van een ander vinden?
- hoe voeg je een gitnore file toe? (zodat je niet alle bak files ziet)
- wie maakt een nieuw project aan? (Repository)

**Comment by tomreit1** [comment]
eerste training gegeven, nu gaan we er met zn alle mee werken. vervolg training moet nog worden ingepland.
